# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b1e550931a7688b0b7e8e023c89e2ab0e086f9f140b30a5dcd1855466b8ca91ad84d054898eb2ebfbed0cc30a7292f83884087e929d5826d7982fb726ac5ce6

test:
  secret_key_base: 89a767c26f8d532b1369b97d01a0923b82b445ee2814fbd478848efb1b7bc6fc45181681768c7d0ba82d5dc9a27e369204566edfe2fda9ebe655595bc629c777

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
